name: Machine Learning Client CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [machine-learning-client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Pipenv
        run: |
          python -m pip install pipenv
      
      - name: Install NLTK data
        run: |
          python -m nltk.downloader punkt stopwords wordnet
        env:
          NLTK_DATA: /home/runner/nltk_data 

      - name: Verify pytest-cov Installation
        run: |
          pip show pytest-cov
      
      - name: Run Tests
        working-directory: machine-learning-client
        run: |
          pytest --cov=app.py --cov-report=xml

      - name: Upload coverage to Codecov
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ matrix.subdir }}/coverage.xml
          flags: ${{ matrix.subdir }}
          name: codecov-coverage-report-${{ matrix.subdir }}
