name: Machine Learning Client CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [machine-learning-client]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r machine_learning_client/requirements.txt

      - name: Run Tests
        working-directory: machine_learning_client
        run: |
          pytest --cov=app.py --cov-report=xml
